### ISSUE TITLE
Credentials in Repo

### ISSUE THREAD

**Issue by shellster** [NoahK200/Web-Projects#1]
Hi,  

I noticed you have credentials checked into your public repo: https://github.com/NoahK200/Web-Projects/blob/e4e1efba62d2699ecf414202ed8afe45c90b6fbc/SBCSS%20Portal/service/config.php

I highly recommend changing them immediately if you haven't already.

**Comment by NoahK200** [comment]
Hi, 

I appreciate your concern. 
Those are just random credentials I used when testing out the code on localhost. Having them on here pose no security threat to anything of mine. Thanks!
